headers = {
    'Accept': 'application/json,text/plain,*/*',
    'Accept-Language': 'en-US',
    "Accept-Encoding": "gzip, deflate",
    'Tl-Init-Data': '',
    'Priority': "u=1, i",
    'Origin': 'https://bybitcoinsweeper.com',
    'Referer': 'https://bybitcoinsweeper.com/',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Ch-Ua': '"Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    'Sec-Ch-Ua-mobile': '?1',
    'Sec-Ch-Ua-platform': '"Android"',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36',
}